name: Submit to LeetCode

on:
  push:
    paths:
      - 'solution.py'  # Adjust this to match the path to your solution file
  workflow_dispatch:  # Enable manual triggering

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run submission script
      env:
        LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        LEETCODE_CSRFTOKEN: ${{ secrets.LEETCODE_CSRFTOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for committing and pushing changes
      run: |
        python submit_to_leetcode.py
